---
galaxy_info:
  author: Larry Smith Jr.
  description: Role to manage LVM Groups/Logical Volumes. Can be used to create, extend or resize LVM.

  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Ubuntu
    versions:
    - precise
    - trusty
  - name: Debian
    versions:
    - jessie
    - wheezy

  categories:
  - system
dependencies: []
