---
- hosts: "{{hosts_inventory}}"
  become: yes
  tasks:
    - name: install ex900-server package
      yum:
        state: latest
        name: ex900-server
      register: ioutput
      ignore_errors: yes

    - debug:
        var: ioutput

    - name: start the ex900-server service
      service:
        state: started
        name: ex900-server
      register: soutput
      ignore_errors: yes

    - debug:
        var: soutput

    - name: provide this  message if installatin fails
      debug:
        msg: "Install failed"
      #when: ioutput.failed == true
      when: ioutput is failed

    - name: provide this output if service fails
      debug:
        msg: "service start failed"
      #when: soutput.failed == true
      when: soutput is failed

    - name: provide this output if both install and service fails
      debug:
        msg: "playbook failed"
      when: ioutput is failed and soutput is failed
