---
- hosts: "{{hosts_inventory}}"
  become: yes
  vars:
    action: "{{apache}}"
  tasks:
    - name: start httpd service
      service:
        name: httpd
        state: started
      when: apache == 'start'

    - name: restart httpd service
      service:
        name: httpd
        state: restarted
      when: apache == 'restart'

    - name: stop httpd service 
      service:
        name: httpd
        state: stopped
      when: apache == 'stop'
