---
- hosts: "{{hosts_inventory}}"
  become: yes
  vars:
    - action: "{{action}}"
  tasks:
    - name: start httpd service
      service:
        name: httpd
        state: started
      when_action: start

    - name: restart httpd service
      service:
        name: httpd
        state: restarted
      when_action: restart

    - name: stop httpd service 
      service:
        name: httpd
        state: stopped
      when_action: stop
