---
- production:
    web-server:
      - bary782c.mylabserver.com
      - bary783c.mylabserver.com
    config-server:
      - bary784c.mylabserver.com
      - bary785c.mylabserver.com
- non-prod:
    staging:
      - bary781c.mylabserver.com
      - bary782c.mylabserver.com
    integration:
      - bary785c.mylabserver.com
      - bary786c.mylabserver.com
