---
- hosts: 
    - bary783c.mylabserver.com
    - bary786c.mylabserver.com
  become: yes
  tasks:
    - name: stop httpd service on both node3 and node6
      service:
        name: httpd
        state: stopped
