---
web:
    site1:
        - bary781c.mylabserver.com
        - bary782c.mylabserver.com
    site2:
        - bary783c.mylabserver.com
        - bary784c.mylabserver.com
db:
    site1:
        - bary785c.mylabserver.com
        - bary786c.mylabserver.com
    site2:
        - bary783c.mylabserver.com
        - bary785c.mylabserver.com
