---
- hosts: "{{hosts_inventory}}"
  become: yes
  tasks:
    - name: install iscsi package
      yum:
        state: latest
        name: iscsi-initiator-utils
      register: ioutput

    - debug:
        var: ioutput

    - name: start the iscsi service
      service:
        state: started
        name: iscsid
      register: soutput

    - debug:
        var: soutput

    - name: provide this  message if installatin fails
      debug:
        msg: "Install failed"
      when: ioutput.failed == true

    - name: provide this output if service fails
      debug:
        msg: "service start failed"
      when: soutput.failed == true

    - name: provide this output if both install and service fails
      debug:
        msg: "playbook failed"
      when: ioutput.failed == true and soutput.failed == true
